version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Install packages and setup dependencies"
          command: |
            npm run preinstall
            npm i
      - save_cache:
          paths:
            - "/src/nodes_modules"
          key: "npm-packages"

  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: "Run tests with coverage"
          command: |
            npm i
            npm run test

  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run:
          name: "Analyze bundles"
          command: |
            npm i
            npm audit

workflows:
  pr-workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
